name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: detectedBY
    attributes:
      label: Detected By
      description: User who detected the Bug
      placeholder: ex. sn322_MGBGHEC
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: Priority of the Bug
      options:
        - 1
        - 2
        - 3
        - 4
    validations:
      required: true
  - type: dropdown
    id: severity
    attributes:
      label: Severity of the Bug
      options:
        - 1 - Critical
        - 2 - High
        - 3 - Medium
        - 4 - Low
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
